# 목차
- [목차](#목차)
- [1. 프로그램 오류](#1-프로그램-오류)
  - [1.1. Java의 런타임 에러](#11-java의-런타임-에러)
  - [1.2. 예외 클래스의 계층 구조](#12-예외-클래스의-계층-구조)
- [2. 예외 처리하기](#2-예외-처리하기)
  - [2.1. try-catch에서의 흐름](#21-try-catch에서의-흐름)

# 1. 프로그램 오류

`컴파일 에러` 
- 컴파일 시에 발생하는 에러
- `javac`: 구문체크, 번역, 최적화, 생략된 코드 추가(extends Object)

> system.out.println(args[0]);

`런타임 에러`
- 실행 시에 발생하는 에러
> System.out.println(args[0]);

`논리적 에러`
- 실행은 되지만, 의도와 다르게 동작하는 것

## 1.1. Java의 런타임 에러

`에러(error)`
- 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
- 메모리 부족 (OutOfMemoryError)

`예외(exception)`
- 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

## 1.2. 예외 클래스의 계층 구조

```java
                                 Object
                                    │
                                Throwable
                ┌──────────────────────────────────┐
            Exception                            Error
┌──────────────────────────┐          ┌──────────────────────────┐          
RuntimeException ...   IOException   ...                   OutOfMemoryError
```

```java
Exception 
  └─ IOexcption 
  └─ ClassNotFoundException 
  └─ ...
  └─ RuntimeException
        └─ ArithmeticException // 0을 0으로 나눴을 때
        └─ nullPointerException
        └─ ...
```
# 2. 예외 처리하기

```java
try {
    // 예외가 발생할 가능성이 있는 문장들을 넣는다.
} catch (Exception1 e1) {
    // Exception1 발생했을 경우, 이를 처리하기 위한 문장
} catch (Exception2 e2) {
    // Exception2 발생했을 경우, 이를 처리하기 위한 문장
} catch (Exception3 e3) {
    // Exception3 발생했을 경우, 이를 처리하기 위한 문장
}

```
- try-catch`{ }` 괄호 생략 불가

## 2.1. try-catch에서의 흐름

> try블럭 내에서 예외가 발생한 경우
1. 발생한 예외가 일치하는 catch 블럭이 있는지 확인한다.
2. 일치하는 catch 블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch 문을 빠져나가서 그 다음 문장을 계속해서 수행한다. <br>
일치하는 catch블럭을 찾지 못하면, 예외는 처리되지 못한다.

> try블럭 내에서 예외가 발생하지 않은 경우
1. catch 블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.